modLoader="javafml"
loaderVersion="[35,)"
#issueTrackerURL="http://my.issue.tracker/"
license="All rights reversed"

[[mods]]
modId="stepup"
version="${version}"
state="Working"
displayName="StepUp"
#updateJSONURL="http://myurl.me/"
displayURL="https://www.curseforge.com/minecraft/mc-mods/stepup"
logoFile="logo.png"
credits="NotTooManyItems, frakier, Emirhangg, Bletch1971"
authors="NotTooManyItems"
description='''
3 options allow you to choose between no auto jump, Minecraft auto jump, and StepUp auto jump
'''

[[dependencies.stepup]]
modId="forge"
mandatory=true
versionRange="[35,)"
ordering="NONE"
side="BOTH"

[[dependencies.stepup]]
modId="minecraft"
mandatory=true
versionRange="[1.16.4,1.17)"
ordering="NONE"
side="CLIENT"
