modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"

[[mods]] #mandatory
modId="stepup" #mandatory
version="1.18.0-0.1.1" #mandatory
state="Working"
displayName="StepUp" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/stepup" #optional
logoFile="logo.png" #optional
credits="NotTooManyItems, frakier, Emirhangg, Bletch1971" #optional
authors="NotTooManyItems" #optional
description='''
3 options allow you to choose between no auto jump, Minecraft auto jump, and StepUp auto jump
'''

[[dependencies.stepup]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[37,)" #mandatory
    ordering="NONE"
    side="CLIENT"

[[dependencies.stepup]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="CLIENT"
